import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export async function getStaticProps(){
  const resp = await fetch(`https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json`)

  return{
    props:{
      pokemon: await resp.json()
    }
  }
}


export default function Home({pokemon}) {
  return (
    <div>
        <Head>
          <title>pokemon Apps</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.card}>
          {pokemon.map((pokemon) => (
            <div className={styles.grid} key={pokemon.id}>
              <Link href={`/pokemon/${pokemon.id}`}>
                <a>
                  <img src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon.image}`} />
                  <div>
                    <h5>{pokemon.name}</h5>
                  </div>
                </a>
              </Link>
            </div>
          ))}
        </div>
    </div>
  )
}

